# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=1025),
        ),
    ]
