# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
