# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170603_1751'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([]),
        ),
    ]
