# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.CharField(default=datetime.datetime(2017, 6, 7, 11, 58, 12, 322299, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
