# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Prediction',
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['slug']},
        ),
    ]
