# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['slug']},
        ),
    ]
