# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0011_auto_20170712_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediction',
            options={},
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='score',
            new_name='predicted',
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_already_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together=set([('user', 'movie')]),
        ),
    ]
